### ISSUE TITLE
Upgrade to latest lerna

### ISSUE THREAD

**Issue by echarles** [datalayer/metarepo#12]
Did a quick test, but the packages are not found

```
"lerna": "8.0.2",
```

```
(datalayer) echarles@echarles:~/Desktop/metarepo$ yarn ls
lerna notice cli v8.0.2
lerna info versioning independent
lerna success found 0 packages
(datalayer) echarles@echarles:~/Desktop/metarepo$ 
```

**Comment by fcollonval** [comment]
The reason is explained there:

https://github.com/lerna/lerna/issues/3416

Packages listed in the gitignore files are ... well ... ignored by lerna v7+

**Comment by echarles** [comment]
Damned.

This metarepo is moving to a copier approach https://github.com/datalayer/metarepo/pull/11, so we could just for now remove the .gitignore entries.
