### ISSUE TITLE
Requirements section should be adapted or put under the Usage one.

### ISSUE THREAD

**Issue by aelskens** [datalayer/metarepo#5]
Either specify that the `environment.yml` comes from this repo (in the *Requirements* section) or put it in the *Usage* section after the cloning part.

**Comment by aelskens** [comment]
Precise that yarn should be installed.

**Comment by echarles** [comment]
> Precise that yarn should be installed.

Yarn is defined in the environement yml, so if you activate the env, it has not to be installed.
